
name: Demo Runner
on: [push,workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get git
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: "18"
      - name: install dependency
        run: npm ci    
      - name: lint it
        run: npm run lint
      - name: test it
        run: npm run test
      - name: build it
        run: npm run build